update

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -1,6 +1,13 @@
 #!/usr/bin/env bash
 
 CONFIG_FILE=".env"
+
+if [ ! -f $CONFIG_FILE ]; then
+  echo "Error: Configuration file '$CONFIG_FILE' not found."
+  echo "Run 'scripts/configure' to configure your module."
+  exit 1
+fi
+
 source $CONFIG_FILE
 
 VERSION=${VERSION:-v0.0.0}
@@ -13,7 +20,7 @@ if [ -z $MODEL_NAME ] || [ -z $MODEL_VERSION ] || [ -z $DOCKER_IMAGE ]; then
 fi
 
 for arg in $@; do
-  if [ $1 == "--local" ] || [ $1 == "-l" ]; then
+  if [ $arg == "--local" ] || [ $arg == "-l" ]; then
     echo "Building the Docker image and loading it into the local Docker daemon..."
     local=true
   fi
@@ -51,7 +58,7 @@ ARCH=$(uname -m)
 os_arch="unsupported_arch"
 
 # Use a case statement to map architectures
-case "$ARCH" in
+case $ARCH in
 "arm64" | "aarch64")
   os_arch="arm64"
   ;;
@@ -62,36 +69,60 @@ esac
 
 platform="linux/amd64"
 
-if [ $local ]; then
+if [ -z $local ]; then
+  platform="linux/$os_arch"
+else
   if [ $os_arch == "unsupported_arch" ]; then
     echo "❌ Error: Unsupported local architecture detected."
-    echo "⛔️ Run $(build) without the $(--local) flag to push the Docker image to Docker Hub for a supported platform."
+    echo "⛔️ Build without the '--local' flag to push the Docker image to Docker Hub for a supported platform."
     echo "👉 scripts/build"
     exit 1
-  else
-    platform="linux/$os_arch"
   fi
 fi
 
 echo Building Docker image: $DOCKER_IMAGE...
 
 # Build argument for model name and version
-MODEL_ID="${MODEL_NAME}:${MODEL_VERSION}"
-DOCKER_HUB_REPO="${DOCKER_HUB_USERNAME}/${DOCKER_IMAGE}"
-
-docker buildx build --build-arg MODEL_ID=$MODEL_ID --platform $platform \
-  -t $DOCKER_HUB_REPO:latest \
-  -t $DOCKER_HUB_REPO:$VERSION \
-  ${local:+--load} ${local:---push} \
-  ${no_cache:+--no-cache} \
-  .
+MODEL_ID=$MODEL_NAME:$MODEL_VERSION
+DOCKER_HUB_REPO=$DOCKER_HUB_USERNAME/$DOCKER_IMAGE
 
 if [ -z $local ]; then
+  tags=(
+    -t $DOCKER_HUB_REPO:latest
+    -t $DOCKER_HUB_REPO:$VERSION
+    --push
+  )
+else
+  tags=(
+    -t $DOCKER_IMAGE:latest
+    -t $DOCKER_IMAGE:$VERSION
+    --load
+  )
+fi
+
+docker buildx build \
+  --build-arg MODEL_ID=$MODEL_ID \
+  --platform $platform \
+  ${tags[@]} \
+  ${no_cache:+--no-cache} \
+  . || exit 1
+
+if [ -z $local ]; then
+  index_digest=$(docker manifest inspect $DOCKER_HUB_REPO:$VERSION | jq -r '.manifests[] | select(.platform.architecture == "amd64" and .platform.os == "linux") | .digest')
   echo "✅ Docker image built and published to Docker Hub successfully."
-  echo -e "\thttps://hub.docker.com/repository/docker/$DOCKER_HUB_REPO/general"
-  echo -e "\n\tscripts/run"
-  sed -i "" "s/^VERSION=.*/VERSION=$VERSION/" .env
-  echo $(docker manifest inspect $DOCKER_HUB_REPO:$VERSION | jq -r '.manifests[] | select(.platform.architecture == "amd64" and .platform.os == "linux") | .digest')
+  echo "1.) Visit the URL to the new Docker image below and copy the index digest:"
+  echo -e "\t👉 https://hub.docker.com/repository/docker/$DOCKER_HUB_REPO/tags/$VERSION/$index_digest"
+  echo "2.) Update the Image field of the module template file:"
+  echo -e "\t👉 lilypad_module.json.tmpl"
+  echo "3.) Commit and push the changes to GitHub, then run the module:"
+  echo -e "\t👉 scripts/run"
+  if [[ $OSTYPE == "darwin"* ]]; then
+    # macOS
+    sed -i "" "s/^VERSION=.*/VERSION=$VERSION/" .env
+  else
+    # Linux and others
+    sed -i "s/^VERSION=.*/VERSION=$VERSION/" .env
+  fi
 else
   echo "✅ Docker image built and loaded into local daemon successfully."
   echo -e "\n\tscripts/run --local"
